name: "Download Reports"

description: "Download Reports from QA tools"

inputs:
  report-directory:
    description: What folder to download reports to.
    required: false
    default: ./reports
    type: string
  test:
    description: Wether to download test execution results.
    required: false
    default: false
    type: boolean
  coverage:
    description: Wether to download test coverage results.
    required: false
    default: false
    type: boolean
  isort:
    description: Wether to download sort changes results.
    required: false
    default: false
    type: boolean
  black:
    description: Wether to download format changes results.
    required: false
    default: false
    type: boolean
  mypy:
    description: Wether to download static type changes results.
    required: false
    default: false
    type: boolean
  flake8:
    description: Wether to download pylint linter changes results.
    required: false
    default: false
    type: boolean
  pylint:
    description: Wether to download flake8 linter changes results.
    required: false
    default: false
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Download PyTest Execution Report
      continue-on-error: true
      if: inputs.test
      uses: actions/download-artifact@v3
      with:
        name: pytest-exec-results
        path: ${{ inputs.report-directory }}

    - name: Download PyTest Coverage Report
      continue-on-error: true
      if: inputs.coverage
      uses: actions/download-artifact@v3
      with:
        name: pytest-cov-results
        path: ${{ inputs.report-directory }}

    - name: Download Bandit Report
      continue-on-error: true
      if: inputs.bandit
      uses: actions/download-artifact@v3
      with:
        name: bandit-results
        path: ${{ inputs.report-directory }}

    - name: Download PyLint Report
      continue-on-error: true
      if: inputs.pylint
      uses: actions/download-artifact@v3
      with:
        name: pylint-results
        path: ${{ inputs.report-directory }}

    - name: Download Flake8 Report
      continue-on-error: true
      if: inputs.flake
      uses: actions/download-artifact@v3
      with:
        name: flake-results
        path: ${{ inputs.report-directory }}

    - name: Download isort Report
      continue-on-error: true
      if: inputs.isort
      uses: actions/download-artifact@v3
      with:
        name: isort-results
        path: ${{ inputs.report-directory }}

    - name: Download Black Report
      continue-on-error: true
      if: inputs.black
      uses: actions/download-artifact@v3
      with:
        name: black-results
        path: ${{ inputs.report-directory }}

    - name: Download MyPy Report
      continue-on-error: true
      if: inputs.mypy
      uses: actions/download-artifact@v3
      with:
        name: mypy-results
        path: ${{ inputs.report-directory }}
