name: "Build and Push Image"
description: "Build and Push Image to the Registry"
runs:
  using: "composite"
  steps:
    # - name: Set SSH agent
    #   uses: webfactory/ssh-agent@v0.5.4
    #   with:
    #     ssh-private-key: |
    #       ${{ secrets.DEPLOY_KEY }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    # - name: Configure AWS Credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
    #     aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      uses: docker/setup-Buildx-action@v2
      id: Buildx

    - name: Build and Push to ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: my-ecr-repo
        IMAGE_TAG: ${{ github.sha }}
      uses: docker/build-push-action@v3
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        builder: ${{ steps.buildx.outputs.name }}
        context: ./Project-Template/API/
        push: true
        file: ./Project-Template/API/Dockerfile
        ssh: default=${{ env.SSH_AUTH_SOCK }}
        tags: $REGISTRY/$REPOSITORY:$IMAGE_TAG
