name: "Build and Push Image"
description: "Build and Push Image to the Registry"
inputs:
  iam-role:
    description: IAM role to assume.
    required: true
    type: string

  aws-region:
    description: AWS Region.
    required: true
    default: us-east-1
    type: string

  ecs-cluster:
    description: AWS ECS Cluster.
    required: true
    type: string

  ecs-service:
    description: AWS ECS Service.
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ inputs.iam-role }}
        role-session-name: TemplateSession
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Image
      id: build
      uses: ./.github/actions/deploy-image
      with:
        dockerfile: ./Project-Template/API/Dockerfile
        context: ./Project-Template
        tags: amazon/amazon-ecs-sample:latest

    - name: Render Amazon ECS task definition
      id: render-app
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: app
        image: amazon/amazon-ecs-sample:latest
        environment-variables: "LOG_LEVEL=info"

    - name: Deploy to Amazon ECS service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.render-app.outputs.task-definition }}
        cluster: ${{ inputs.ecs-cluster}}
        service: ${{ inputs.ecs-service }}
