name: "Cache Dependencies"
description: "Setup Python with pip Cache and Install Dependencies"
inputs:
  app-directory:
    description: What folder to search for requirements
    required: true
    type: string
outputs:
  app-directory:
    description: App Deps Directory
    value: ${{ inputs.app-directory }}

runs:
  using: "composite"
  steps:
    - name: Setup Python with pip Cache
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
        cache-dependency-path: |
          **/requirements*.txt
          **/setup.py

    - name: Current Dir
      run: pwd
    - name: Install Application Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash

    - name: Install QA Dependencies
      run: |
        pip install --upgrade isort black mypy flake8 pylint
        if [ -f requirements-qa.txt ]; then pip install -r requirements-qa.txt; fi
      shell: bash

    - name: Install Security Dependencies
      run: |
        pip install --upgrade bandit
        if [ -f requirements-sec.txt ]; then pip install -r requirements-sec.txt; fi
      shell: bash

    - name: Install Test Dependencies
      env:
        requirements_path:
      run: |
        pip install --upgrade pytest pytest-cov
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
      shell: bash
