name: Main Workflow

on:
  workflow_call:
    inputs:
      cache-paths:
        required: true
        type: string

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-python@v4
          with:
            python-version: "3.9"
            cache: "pip"
            cache-dependency-path: |
              app/componentA/requirements.txt
              app/componentB/requirements.txt
        - run: |
            python -m pip install --upgrade pip
            pip install -r app/componentA/requirements.txt
            pip install -r app/componentB/requirements.txt
