name: "Cache Dependencies"
description: "Setup Python with pip Cache and Install Dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup Python with pip Cache
      id: cache
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
        cache-dependency-path: |
          **/requirements*.txt
          **/setup.py

    - name: Install Application Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install ./Project-Template/Databases/MemoryDB
        pip install ./Project-Template/Databases/MongoDB
        pip install ./Project-Template/Business
        pip install ./Project-Template/API
      shell: bash

    - name: Install QA Dependencies
      run: |
        pip install --upgrade isort black mypy flake8 pylint
        if [ -f ./Project-Template/requirements-qa.txt ]; then pip install -r ./Project-Template/requirements-qa.txt; fi
      shell: bash

    - name: Install Security Dependencies
      run: |
        pip install --upgrade bandit
        if [ -f ./Project-Template/requirements-sec.txt ]; then pip install -r ./Project-Template/requirements-sec.txt; fi
      shell: bash

    - name: Install Test Dependencies
      run: |
        pip install --upgrade pytest pytest-cov
        if [ -f ./Project-Template/requirements-test.txt ]; then pip install -r ./Project-Template/requirements-test.txt; fi
      shell: bash
