name: "Cache Dependencies"
description: "Setup Python with pip Cache and Install Dependencies"
runs:
  using: "composite"
  steps:
    - name: Setup Python with pip Cache
      id: cache
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
        cache-dependency-path: |
          **/requirements*.txt
          **/setup.py

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r ./Project-Template/requirements.txt
        pip install -r ./Project-Template/API/requirements.txt
        pip install ./Project-Template/Business
        pip install ./Project-Template/Databases/MemoryDB
      shell: bash
