name: "Echo Env"

description: "Echo message input"

inputs:
  message:
    description: message
    required: false
    default: "."
    type: string

runs:
  using: "composite"

  steps:
    - name: Print env message
      run: echo "${{inputs.message}}"
      shell: bash
