name: Deployment Workflow

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Config:
    runs-on: ubuntu-latest
    env:
      CONTEXT: ./Project-Template
      ECR_REPOSITORY: gha-test-repo
      IMAGE_TAG: ${{ github.sha }}
    outputs:
      app-context: ${{ steps.context.outputs.context }}
      tag: ${{ steps.image-tag.outputs.tag }}
    steps:
      - name: Set Context Directory
        id: context
        run: echo context=$CONTEXT >> $GITHUB_OUTPUT

      - name: Set Image Tag
        id: image-tag
        run: echo tag=$ECR_REPOSITORY:$IMAGE_TAG >> $GITHUB_OUTPUT

  Deploy:
    needs: [Config]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::306094223949:role/gha-template-role
          role-session-name: templatesession
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-Buildx-action@v2
        id: buildx

      - name: Build and Push Image
        id: build-image
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ needs.Config.outputs.app-context }}
          file: ${{ needs.Config.outputs.app-context }}/Dockerfile
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ needs.Config.outputs.tag }}
          push: True

      - name: Download Task Definition
        env:
          TASK_DEFINITION: template-task
        run: |
          aws ecs describe-task-definition --task-definition $TASK_DEFINITION --query taskDefinition > task-definition.json

      - name: Update Task Definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: template
          image: ${{ steps.build-image.outputs.imageid }}

      - name: Deploy Task Definitions
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: template-service
          cluster: default
          wait-for-service-stability: false
