name: Deployment Workflow

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::306094223949:role/GHA-Template-Role
          role-session-name: TemplateSession
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-Buildx-action@v2
        id: buildx

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          # ssh: default=${{ env.SSH_AUTH_SOCK }}
          context: ./Project-Template
          file: ./Project-Template/Dockerfile
          tags: 306094223949.dkr.ecr.us-east-1.amazonaws.com/gha-test-repo:${{ github.sha }}
          push: True
