name: Integration Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Cache & Dependencies
        uses: ./.github/actions/cache-dependencies

  Quality:
    needs: [Build]
    uses: ./.github/workflows/reusable-qa.yml
    with:
      module-directory: ./Project-Template

  Security:
    needs: [Build]
    uses: ./.github/workflows/reusable-security.yml
    with:
      module-directory: ./Project-Template

  Test:
    needs: [Build]
    uses: ./.github/workflows/reusable-test.yml
    with:
      module-directory: ./Project-Template

  Report:
    needs: [Quality, Security, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Report
        run: echo "Report"
