name: Integration Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

defaults:
  run:
    shell: bash
    working-directory: ./Project-Template

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Cache & Dependencies
        uses: ./.github/actions/cache-dependencies
        with: # Allowed expression contexts: github, and needs.
          app-directory: ./Project-Template

  Quality:
    needs: [Build]
    uses: ./.github/workflows/reusable-qa.yml
    with:
      app-directory: ${{needs.Build.outputs.app-directory}}
      module-directory: ./Project-Template

  Security:
    needs: [Build]
    uses: ./.github/workflows/reusable-security.yml
    with:
      app-directory: ${{needs.Build.outputs.app-directory}}
      module-directory: ./Project-Template

  Test:
    needs: [Build]
    uses: ./.github/workflows/reusable-test.yml
    with:
      app-directory: ${{needs.Build.outputs.app-directory}}
      module-directory: ./Project-Template

  # Report:
  #   needs: [Build] #[Quality, Security, Test]
  #   if: always()
  #   uses: ./.github/workflows/reusable-report.yml
