name: Integration Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

env:
  APP: ./Project-Template
  MODULE: ./Project-Template

jobs:
  Config:
    runs-on: ubuntu-latest
    outputs:
      app-directory: ${{ steps.app-dir.outputs.dir }}
      module-directory: ${{ steps.module-dir.outputs.dir }}
    steps:
      - name: Set Dependencies Directory
        id: app-dir
        run: echo dir=$APP >> $GITHUB_OUTPUT

      - name: Set DUT Directory
        id: module-dir
        run: echo dir=$MODULE >> $GITHUB_OUTPUT

  Build:
    needs: [Config]
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout Repository
      #   uses: actions/checkout@v3

      - name: Setup Cache & Dependencies
        uses: cristovamsilva/python-dependencies-action@v1
        with:
          app-directory: ${{ needs.Config.outputs.app-directory }}

  Quality:
    needs: [Config, Build]
    uses: ./.github/workflows/reusable-qa.yml
    with:
      app-directory: ${{ needs.Config.outputs.app-directory }}
      module-directory: ${{ needs.Config.outputs.module-directory }}

  Security:
    needs: [Config, Build]
    uses: ./.github/workflows/reusable-security.yml
    with:
      app-directory: ${{ needs.Config.outputs.app-directory }}
      module-directory: ${{ needs.Config.outputs.module-directory }}

  Test:
    needs: [Config, Build]
    uses: ./.github/workflows/reusable-test.yml
    with:
      app-directory: ${{ needs.Config.outputs.app-directory }}
      module-directory: ${{ needs.Config.outputs.module-directory }}

  # Report:
  #   # needs: [Quality, Security, Test]
  #   uses: ./.github/workflows/reusable-report.yml
  #   with:
  #     message: ${{ env.APP }}
