name: Integration Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
env:
  MODULE: ./Project-Template

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Cache & Dependencies
        uses: ./.github/actions/cache-dependencies

  Quality:
    needs: [Build]
    uses: ./.github/workflows/reusables/reusable-qa.yml
    with:
      module-directory: $MODULE

  Security:
    needs: [Build]
    uses: ./.github/workflows/reusables/reusable-security.yml
    with:
      module-directory: $MODULE

  Test:
    needs: [Build]
    uses: ./.github/workflows/reusables/reusable-test.yml
    with:
      module-directory: $MODULE

  Report:
    needs: [Quality, Security, Test]
    if: always()
    uses: ./.github/workflows/reusables/reusable-report.yml
