name: Integration Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

env:
  APP: ./Project-Template
  MODULE: ./Project-Template

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Cache & Dependencies
        uses: ./.github/actions/cache-dependencies
        with:
          app-directory: ${{ env.APP }}

  Quality:
    needs: [Build]
    uses: ./.github/workflows/reusable-qa.yml
    with:
      app-directory: ${{ env.APP }}
      module-directory: ${{ env.MODULE }}

  Security:
    needs: [Build]
    uses: ./.github/workflows/reusable-security.yml
    with:
      app-directory: ${{ env.APP }}
      module-directory: ${{ env.MODULE }}

  Test:
    needs: [Build]
    uses: ./.github/workflows/reusable-test.yml
    with:
      app-directory: ${{ env.APP }}
      module-directory: ${{ env.MODULE }}

  Report:
    needs: [Quality, Security, Test]
    if: always()
    uses: ./.github/workflows/reusable-report.yml
