name: Integration Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

env:
  APP: ./Project-Template
  MODULE: ./Project-Template/Module-Dir

jobs:
  Config:
    runs-on: ubuntu-latest
    outputs:
      app-directory: ${{ steps.app-dir.outputs.dir }}
      module-directory: ${{ steps.module-dir.outputs.dir }}
    steps:
      - name: Set Dependencies Directory
        id: app-dir
        run: echo "dir=$APP >> $GITHUB_OUTPUT

      - name: Set DUT Directory
        id: module-dir
        run: echo "dir=$MODULE" >> $GITHUB_OUTPUT

  Build:
    needs: [Config]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Cache & Dependencies
        uses: ./.github/actions/cache-dependencies
        with: # Allowed expression contexts: github, and needs.
          app-directory: ${{needs.Config.outputs.app-directory}}

  # Quality:
  #   needs: [Build]
  #   uses: ./.github/workflows/reusable-qa.yml
  #   with:
  #     app-directory: ${{needs.Build.outputs.app-directory}}
  #     module-directory: ./Project-Template

  # Security:
  #   needs: [Build]
  #   uses: ./.github/workflows/reusable-security.yml
  #   with:
  #     app-directory: ${{needs.Build.outputs.app-directory}}
  #     module-directory: ./Project-Template

  # Test:
  #   needs: [Build]
  #   uses: ./.github/workflows/reusable-test.yml
  #   with:
  #     app-directory: ${{needs.Build.outputs.app-directory}}
  #     module-directory: ./Project-Template

  Report:
    # needs: [Quality, Security, Test]
    if: always()
    uses: ./.github/workflows/reusable-report.yml
    with:
      message: ${{ github.env }}
