name: Main Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: |
            Project-Template/API/requirements.txt
            Project-Template/Business/requirements.txt
            Project-Template/Databases/MemoryDB/requirements.txt
            Project-Template/Databases/MongoDB/requirements.txt
      - run: |
          python -m pip install --upgrade pip
          pip install ./Project-Template/Databases/MemoryDB
          pip install ./Project-Template/Business

  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Lint"

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test"

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy"

  report:
    needs: [lint, test, deploy]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Report"
