name: Main Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Setup Python and Cache Dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: |
            Project-Template/API/requirements.txt
            Project-Template/Business/requirements.txt
            Project-Template/Databases/MemoryDB/requirements.txt
            Project-Template/Databases/MongoDB/requirements.txt
      - run: |
          python -m pip install --upgrade pip
          pip install ./Project-Template/Databases/MemoryDB
          pip install ./Project-Template/Business
