name: Main Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Cache & Dependencies
        uses: ./.github/actions/cache-dependencies

  CodeQuality:
    needs: [Build]
    uses: ./.github/workflows/reusable.yml

  Test:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Cache & Dependencies
        uses: ./.github/actions/cache-dependencies

      - name: Check Coverage
        continue-on-error: true
        run: echo "Coverage 100%"

      - name: Test with pytest
        run: echo "Tests"

  Deploy:
    needs: [Build, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-Buildx-action@v2
        id: Buildx

  Report:
    needs: [CodeQuality, Deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Report
        run: echo "Report"
