name: Reusable QA
on:
  workflow_call:
    inputs:
      app-directory:
        description: What folder to search for requirements
        required: true
        type: string
      module-directory:
        description: What folder to analyzie
        required: true
        type: string
      sort:
        description: Whether to run isort.
        required: false
        default: true
        type: boolean
      format:
        description: Whether to run black.
        required: false
        default: true
        type: boolean
      StaticTypeCheck:
        description: Whether to run black.
        required: false
        default: true
        type: boolean
      lint-with-flake8:
        description: Whether to run flake8.
        required: false
        default: true
        type: boolean
      lint-with-pylint:
        description: Whether to run pylint.
        required: false
        default: true
        type: boolean

jobs:
  Sort:
    runs-on: ubuntu-latest
    steps:
      - name: Load Cache & Dependencies
        uses: cristovamsilva/python-dependencies-action@v1
        with:
          app-directory: ${{ inputs.app-directory }}

      - name: Sort Imports using isort
        continue-on-error: true
        if: inputs.sort
        run: isort ${{ inputs.module-directory }} --diff

  Format:
    runs-on: ubuntu-latest
    steps:
      - name: Load Cache & Dependencies
        uses: cristovamsilva/python-dependencies-action@v1
        with:
          app-directory: ${{ inputs.app-directory }}

      - name: Format using Black
        continue-on-error: true
        if: inputs.format
        run: black ${{ inputs.module-directory }} --diff --color

  StaticTypeCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Load Cache & Dependencies
        uses: cristovamsilva/python-dependencies-action@v1
        with:
          app-directory: ${{ inputs.app-directory }}

      - name: Format using Black
        continue-on-error: true
        if: inputs.StaticTypeCheck
        run: mypy ${{ inputs.module-directory }}

  Lint-Pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Load Cache & Dependencies
        uses: cristovamsilva/python-dependencies-action@v1
        with:
          app-directory: ${{ inputs.app-directory }}

      - name: Lint with pylint
        continue-on-error: true
        if: inputs.lint-with-pylint
        run: pylint ${{ inputs.module-directory }} --output-format=parseable

  Lint-Flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Load Cache & Dependencies
        uses: cristovamsilva/python-dependencies-action@v1
        with:
          app-directory: ${{ inputs.app-directory }}

      - name: Lint with flake8
        continue-on-error: true
        if: inputs.lint-with-flake8
        run: flake8 ${{ inputs.module-directory }} --count --exit-zero --select=E9,F63,F7,F82 --show-source --statistics
