name: Reusable Cache
on:
  workflow_call:

jobs:
  CodeQuality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load Cache & Dependencies
        uses: ./.github/actions/cache-dependencies
