name: Reusable QA
on:
  workflow_call:
    inputs:
      module-directory:
        description: What folder to analyzie
        required: true
        type: string
      scan-with-sonarcloud:
        description: Wheter Sonar Cloud should be used.
        required: false
        default: false
        type: boolean
    secrets:
      SONAR_TOKEN:
        description: sonarcloud token
        required: false

jobs:
  SortAndFormat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load Cache & Dependencies
        uses: ./.github/actions/cache-dependencies

      - name: Sort Imports using isort
        run: isort ${{ inputs.module-directory }} --diff

      - name: Format using Black
        run: black ${{ inputs.module-directory }} --diff --color

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load Cache & Dependencies
        uses: ./.github/actions/cache-dependencies

      - name: Lint with pylint
        continue-on-error: true
        run: pylint ${{ inputs.module-directory }}

      - name: Lint with flake8
        continue-on-error: true
        run: flake8 ${{ inputs.module-directory }}

  VerifySecurity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load Cache & Dependencies
        uses: ./.github/actions/cache-dependencies
      - name: Verify with Bandit
        continue-on-error: true
        run: bandit -r ${{ inputs.module-directory }}

  SonarCloud:
    runs-on: ubuntu-latest
    if: inputs.scan-with-sonarcloud
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Disabling shallow clone is recommended for improving relevancy of reporting
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
