name: Reusable Security
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: sonarcloud token
        required: false
      SONARQUBE_TOKEN:
        description: sonarqube token
        required: false
      SONARQUBE_HOST:
        description: sonarcloud host
        required: false
    inputs:
      app-directory:
        description: What folder to search for requirements
        required: true
        type: string
      module-directory:
        description: What folder to analyzie
        required: true
        type: string
      dependency-review:
        description: Verify problems with dependencies
        required: false
        default: false
        type: boolean

jobs:
  Bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Load Cache & Dependencies
        uses: cristovamsilva/python-dependencies-action@v1
        with:
          app-directory: ${{ inputs.app-directory }}

      - name: Verify with Bandit
        continue-on-error: true
        run: bandit -r ${{ inputs.module-directory }}

  Dependency-Review:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: inputs.dependency-review
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          config-file: "./.github/dependency-review-config.yml"
