name: Reusable Security
on:
  workflow_call:
    inputs:
      app-directory:
        description: What folder to search for requirements
        required: true
        type: string
      module-directory:
        description: What folder to analyzie
        required: true
        type: string
      bandit:
        description: Whether to scan with Bandit.
        required: false
        default: true
        type: boolean
      dependency-review:
        description: Verify problems with dependencies.
        required: false
        default: false
        type: boolean

jobs:
  Bandit:
    runs-on: ubuntu-latest
    if: inputs.bandit
    steps:
      - name: Load Cache & Dependencies
        uses: cristovamsilva/python-dependencies-action@v1
        with:
          app-directory: ${{ inputs.app-directory }}

      - name: Verify with Bandit
        continue-on-error: true
        run: bandit -r ${{ inputs.module-directory }}

  Dependency-Review:
    runs-on: ubuntu-latest
    if: github.event.pull_request
    continue-on-error: true
    if: inputs.dependency-review
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          config-file: "./.github/dependency-review-config.yml"
