name: Reusable Security Check Workflow
on:
  workflow_call:
    inputs:
      deps-directory:
        description: What folder to search for requirements.
        required: false
        default: "."
        type: string
      source-directory:
        description: Directory containing the source code.
        required: true
        type: string
      module-directory:
        description: Directory containing a specific module source code.
        required: false
        default: .
        type: string

      bandit:
        description: Whether to run bandit.
        required: false
        default: true
        type: boolean
      deps-review:
        description: Whether to run bandit.
        required: false
        default: true
        type: boolean

    outputs:
      bandit_report_path:
        description: "Bandit Report Path"
        value: ${{ jobs.Bandit.outputs.report_path }}

jobs:
  Bandit:
    runs-on: ubuntu-latest
    if: inputs.bandit
    env:
      REPORT_FILE: bandit
      REPORT_TYPE: json
    outputs:
      report_path: bandit-results/bandit.xml
    steps:
      - name: Output Report File
        id: report-file
        run: echo file=$REPORT_FILE.$REPORT_TYPE >> GITHUB_OUTPUT

      - name: Verify with Bandit
        uses: cristovamsilva/run-and-report-action@main
        with:
          deps-directory: ${{ inputs.deps-directory }}
          security-deps: true
          command: bandit -r ${{ inputs.module-directory }} -f json -o bandit.json
          source-directory: ${{ inputs.source-directory }}
          report: true
          report-key: bandit-results
          report-file: ${{ inputs.source-directory }}/bandit.json

  Dependency-Review:
    runs-on: ubuntu-latest
    if: inputs.deps-review && github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Review Dependencies
        uses: actions/dependency-review-action@v3
        with:
          license-check: false
          config-file: "./.github/dependency-review-config.yml"
