name: Reusable Test
on:
  workflow_call:
    inputs:
      app-directory:
        description: What folder to search for requirements
        required: true
        type: string
      module-directory:
        description: What folder to analyze.
        required: true
        type: string

jobs:
  TestAndCoverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load Cache & Dependencies
        uses: ./.github/actions/cache-dependencies
        with:
          app-directory: ${{ inputs.app-directory }}

      - name: Test Module
        run: pytest ${{ inputs.module-directory }} --cov=${{ inputs.module-directory }}

      # - name: Upload pytest test results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: pytest-results
      #     path: junit/test-results.xml
      #   if: ${{ always() }}
