name: Reusable Test
on:
  workflow_call:
    inputs:
      module-directory:
        description: What folder to analyzie
        required: true
        type: string

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Cache & Dependencies
        uses: ./.github/actions/cache-dependencies

      - name: Test Module
        run: echo "Testing..."

  Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Cache & Dependencies
        uses: ./.github/actions/cache-dependencies

      - name: Verify Coverage
        run: echo "Coverage 100%..."
