name: Reusable QA
on:
  workflow_call:
    inputs:
      module-directory:
        description: What folder to analyzie
        required: true
        type: string
      sort:
        description: Whether to run isort.
        required: false
        default: true
        type: boolean
      format:
        description: Whether to run black.
        required: false
        default: true
        type: boolean
      lint-with-flake8:
        description: Whether to run flake8.
        required: false
        default: true
        type: boolean
      lint-with-pylint:
        description: Whether to run pylint.
        required: false
        default: true
        type: boolean

jobs:
  SortAndFormat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load Cache & Dependencies
        uses: ./.github/actions/cache-dependencies

      - name: Sort Imports using isort
        if: inputs.sort
        run: isort ${{ inputs.module-directory }} --diff

      - name: Format using Black
        if: inputs.format
        run: black ${{ inputs.module-directory }} --diff --color

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load Cache & Dependencies
        uses: ./.github/actions/cache-dependencies

      - name: Lint with pylint
        if: inputs.lint-with-pylint
        continue-on-error: true
        run: pylint ${{ inputs.module-directory }}

      - name: Lint with flake8
        if: inputs.lint-with-flake8
        continue-on-error: true
        run: flake8 ${{ inputs.module-directory }} --count --exit-zero --select=E9,F63,F7,F82 --show-source --statistics
