name: Reusable Test
on:
  workflow_call:
    inputs:
      app-directory:
        description: What folder to search for requirements.
        required: true
        type: string
      module-directory:
        description: What folder to analyze.
        required: true
        type: string

outputs:
  coverage_report_path: ${{ jobs.Test.outputs.coverage }}
  execution_report_path: ${{ jobs.Test.outputs.execution }}
jobs:
  Test:
    runs-on: ubuntu-latest
    env:

    outputs:
      coverage: pytest-cov-results/coverage.xml
      execution: pytest-exec-results/xunit-result.xml
    steps:
      - name: Load Cache & Dependencies
        uses: cristovamsilva/python-dependencies-action@v1
        with:
          app-directory: ${{ inputs.app-directory }}

      - name: Test Module
        continue-on-error: true
        run: pytest --cov=${{ inputs.module-directory }} --cov-report xml --junitxml=xunit-result.xml
        working-directory: ${{ inputs.app-directory }}

      - name: Upload pytest execution results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-exec-results
          path: ${{ inputs.app-directory }}/xunit-result.xml

      - name: Upload pytest coverage results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-cov-results
          path: ${{ inputs.app-directory }}/coverage.xml
