name: Reusable Security
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: sonarcloud token
        required: false
      SONARQUBE_TOKEN:
        description: sonarqube token
        required: false
      SONARQUBE_HOST:
        description: sonarcloud host
        required: false
    inputs:
      module-directory:
        description: What folder to analyzie
        required: true
        type: string
      scan-with-sonarcloud:
        description: Whether to scan with Sonar Cloud.
        required: false
        default: false
        type: boolean
      scan-with-sonarqube:
        description: Whether to scan with Sonar Qube.
        required: false
        default: false
        type: boolean

jobs:
  Bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load Cache & Dependencies
        uses: ./.github/actions/cache-dependencies
        with:
          module-directory: ${{ inputs.module-directory }}

      - name: Verify with Bandit
        continue-on-error: true
        run: bandit -r ${{ inputs.module-directory }}
