name: Reusable SonarCloud
on:
  workflow_call:

jobs:
  SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Reports
        id: download
        uses: actions/download-artifact@v3
        with:
          path: /reports

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ${{steps.download.outputs.download-path}}

      - name: Scan with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
