name: Reusable SonarCloud
on:
  workflow_call:
    inputs:
      exec-report:
        description: Where to retrieve pytest execution results.
        required: false
        default: exec-report.xml
        type: string
      cov-report:
        description: Where to retrieve pytest coverage results.
        required: false
        default: coverage.xml
        type: string
      bandit-report:
        description: Where to retrieve bandit results.
        required: false
        default: bandit.xml
        type: string
      pylint-report:
        description: Where to retrieve pylint results.
        required: false
        default: pylint.xml
        type: string
      flake-report:
        description: Where to retrieve flake results.
        required: false
        default: flake8.xml
        type: string
jobs:
  SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Reports
        id: download
        uses: actions/download-artifact@v3
        with:
          path: reports

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ${{steps.download.outputs.download-path}}

      - name: Scan with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=reports/${{ inputs.cov-report }}
            -Dsonar.sources=Project-Template/
            -Dsonar.verbose=true
          # projectBaseDir: my-custom-directory
