name: Reusable Test
on:
  workflow_call:
    inputs:
      app-directory:
        description: What folder to search for requirements.
        required: true
        type: string
      module-directory:
        description: What folder to analyze.
        required: true
        type: string
      exec-report:
        description: Where to save execution results.
        required: false
        default: exec-report.xml
        type: string
      cov-report:
        description: Where to save coverage results.
        required: false
        default: coverage.xml
        type: string

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Load Cache & Dependencies
        uses: cristovamsilva/python-dependencies-action@v1
        with:
          app-directory: ${{ inputs.app-directory }}

      - name: Test Module
        continue-on-error: true
        run: pytest ${{ inputs.module-directory }} --cov=${{ inputs.module-directory }} --cov-report xml:${{ inputs.cov-report }} --junitxml=${{ inputs.exec-report }}
        working-directory: ${{ inputs.app-directory }}

      - name: Upload pytest execution results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-exec-results
          path: ${{ inputs.app-directory }}/${{ inputs.exec-report }}

      - name: Upload pytest coverage results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-cov-results
          path: ${{ inputs.app-directory }}/${{ inputs.cov-report }}

      - name: Set Artifcats Key Outputs
        run: |
          echo cov-artifact="pytest-cov-results" >> GITHUB_OUTPUT
          echo exc-artifact="pytest-exec-results" >> GITHUB_OUTPUT
