name: Reusable Sonar
on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: sonarcloud token
        required: false
      SONARQUBE_TOKEN:
        description: sonarqube token
        required: false
      SONARQUBE_HOST:
        description: sonarcloud host
        required: false
    inputs:
      module-directory:
        description: What folder to analyzie
        required: true
        type: string
      scan-with-sonarcloud:
        description: Whether to scan with Sonar Cloud.
        required: false
        default: false
        type: boolean
      scan-with-sonarqube:
        description: Whether to scan with Sonar Qube.
        required: false
        default: false
        type: boolean

jobs:
  SonarCloudTrigger:
    runs-on: ubuntu-latest
    if: inputs.scan-with-sonarcloud
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  SonarQubeTrigger:
    runs-on: ubuntu-latest
    if: inputs.scan-with-sonarqube
    steps:
      - uses: actions/checkout@master
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
