name: Reusable Test
on:
  workflow_call:
    inputs:
      module-directory:
        description: What folder to analyzie
        required: true
        type: string

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Cache & Dependencies
        uses: ./.github/actions/cache-dependencies

      - name: Test Module
        run: pytest ${{ inputs.module-directory }} --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: junit/test-results.xml
        if: ${{ always() }}

  # Coverage:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Setup Cache & Dependencies
  #       uses: ./.github/actions/cache-dependencies

  #     - name: Verify Coverage
  #       run: echo "Coverage 100%..."
