name: "Build and Push Image"
description: "Build and Push Image to the Registry"
inputs:
  push:
    description: Whether to push image.
    required: false
    default: true
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-Buildx-action@v2
      id: Buildx

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        builder: ${{ steps.buildx.outputs.name }}
        context: ./Project-Template/
        push: ${{ inputs.push }}
        file: ./Project-Template/API/Dockerfile
        tags: ghcr.io/${{ github.repository_owner }}/test-repo:latest
