name: "Build and Push Image"
description: "Build and Push Image to the Registry"
inputs:
  dockerfile:
    description: Dockerfile Path.
    required: true
    type: string
  context:
    description: Docker Context.
    required: true
    type: string
  ssh:
    description: Whether to configure ssh agent.
    required: false
    default: false
    type: boolean
  deploy-keys:
    description: Deploy keys to use.
    required: false
  push:
    description: Whether to push image.
    required: false
    default: true
    type: boolean

runs:
  using: "composite"
  steps:
    # - name: Set SSH agent
    #   if: inputs.ssh
    #   uses: webfactory/ssh-agent@v0.7.0
    #   with:
    #     ssh-private-key: ${{ inputs.deploy-keys }}

    - name: Set up Docker Buildx
      uses: docker/setup-Buildx-action@v2
      id: Buildx

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: ghcr.io/cristovamsilva/test-repo:latest
